import type { MetadataRoute } from "next";
import { BRAND_BASELINE } from "@/lib/pwa/colors";

// Web app manifest, served by Next at /manifest.webmanifest and auto-linked from
// the document head. Makes TaskFlow installable to the home screen and launches
// it standalone with the brand identity. Icons are generated by app/icon.tsx and
// app/apple-icon.tsx (referenced here by their route paths).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "TaskFlow — Real-time collaborative kanban",
    short_name: "TaskFlow",
    description:
      "A real-time collaborative kanban board — drag tasks, track progress, and collaborate with your team.",
    start_url: "/boards",
    display: "standalone",
    background_color: BRAND_BASELINE,
    theme_color: BRAND_BASELINE,
    icons: [
      // A single scalable SVG covers all sizes; the full-bleed gradient
      // background makes it safe to also serve as a maskable (adaptive) icon.
      { src: "/icon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" },
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "maskable",
      },
    ],
  };
}
